### PR TITLE
Update Wikidata SPARQL converter

### PR DESCRIPTION
**Pull request by rayslxu**
Update the converter to match the new ThingTalk syntax we added in the past year. 
The old code was also problematic. Most of the issues are fixed. Or operator is still broken, we will fix it later.

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
I think this looks good.
I'm not sure about the part where you say "We don't know if a value is represented as a string or an array". Wouldn't we know that from the type?

**Comment by rayslxu** [comment]
> I think this looks good.
> I'm not sure about the part where you say "We don't know if a value is represented as a string or an array". Wouldn't we know that from the type?

do you mean this one: "we don't know if a value is represented as a string or an entity in Wikidata"
Lots of things we considered String is also an entity in wikidata (like given name, last name), so we cannot decide based on thingtalk type.

**Comment by gcampax** [comment]
Yes I meant string or entity (brain fart, probably).
Time to add a new annotation with the wikidata type? We did that for schema.org (even though we didn't really use it)

**Comment by gcampax** [comment]
Mostly I ask because it looks like you're generating some really inefficient SPARQL and I worry things will timeout more often than not.

**Comment by rayslxu** [comment]
> Mostly I ask because it looks like you're generating some really inefficient SPARQL and I worry things will timeout more often than not.

I tested that, in fact there is no significant difference in terms of time. but yeah, we should probably include type information - it's going to be tricky though because the same property can be used for different types of values (even for the same domain). Anyway, it's going to be part of the project to dump the entire wikdiata.

**Pull request merged**
