### PR TITLE
Improve readability of argument annotations

### PR DESCRIPTION
**Pull request by rayslxu**
The current prettyprint format is really not readable especially when we have
a long list of canonical annotations for arguments, to improve readability:
- linebreak for all argument annotations
- linebreak for first level items of json for argument annotations

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
I like this, but how can `#_[formatted]` is not prettyprinted the same way?

**Comment by rayslxu** [comment]
> I like this, but how can `#_[formatted]` is not prettyprinted the same way?

I didn't apply linebreak on arrays to avoid making the output to be extremely long.

**Comment by rayslxu** [comment]
> I like this, but how can `#_[formatted]` is not prettyprinted the same way?

Maybe I can apply it to first level objects in arrays, and things will look like this:
```
#_[formatted=["Here is something for you", {
    type="rdl",
    displayTitle="$title",
    webCallback="$url"
  }]]
```

**Comment by gcampax** [comment]
I see. No I think your end result looks good, no need for changes. I just wanted to understand the implementation.

**Review by gcampax — APPROVED** [review]

**Pull request merged**
